### ISSUE TITLE
No Code in Python Notebook

### ISSUE THREAD

**Issue by jmcrey** [jwine01/pwp-capstones#1]
Unfortunately, it looks like there is currently no code in the uploaded Jupyter notebook. It is possible there was an error while uploading the Jupyter notebook; please try to re-upload the Jupyter notebook to GitHub. Once the code has been re-uploaded, please comment on this issue and mention my username in the comment (e.g. @jmcrey). I will review the notebook in full once it is re-upload.

I am terribly sorry for the inconvenience! If you have any questions, please do not hesitate to reach out.

**Comment by jwine01** [comment]
@jmcrey The commit button available inside the Codecademy did not seem to pull my code, now that you mention it.  I have re-uploaded it with the addition of my name to distinguish the file and be certain I sent the correct one.  Thanks for the notification.

**Comment by jmcrey** [comment]
@jwine01 I have completed the review of the code. Please review the other issues and reach out if you have any questions!
